#!/usr/bin/env python3
"""Generate MoonBit conformance tests from the vendored json-patch-tests
fixtures (suite/fixtures/*.json) into suite/gen/*_wbtest.mbt.

Cases marked "disabled" upstream are skipped and counted in the header.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "suite" / "fixtures"
OUT = ROOT / "suite" / "gen"


def literal(value) -> str:
    """Render a JSON value as a double-escaped MoonBit string literal."""
    text = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def test_name(source: str, index: int, comment: str) -> str:
    slug = re.sub(r"[^0-9A-Za-z]+", "_", comment).strip("_")[:60]
    if not slug:
        slug = "case"
    return f"{source}_{index:03d}_{slug}"


def gen_file(source: Path) -> str:
    cases = json.loads(source.read_text(encoding="utf-8"))
    name = source.stem
    lines = [
        "// Generated by tools/gen_suite.py from suite/fixtures/"
        + source.name
        + " — do not edit.",
        f"// {name}: {len(cases)} cases upstream.",
        "",
    ]
    included = 0
    skipped = 0
    for i, case in enumerate(cases):
        if case.get("disabled"):
            skipped += 1
            continue
        included += 1
        comment = case.get("comment", "")
        tname = test_name(name, i, comment)
        lines.append(f'test "{tname}" {{')
        if comment:
            lines.append(f"  // {comment}")
        lines.append(f"  let doc : Json = @json.parse({literal(case['doc'])})")
        lines.append(
            f"  let patch : Json = @json.parse({literal(case['patch'])})"
        )
        if "expected" in case:
            lines.append(
                f"  let expected : Json = @json.parse("
                f"{literal(case['expected'])})"
            )
            lines.append("  match @jsonpatch.apply_patch(doc, patch) {")
            lines.append(
                "    Ok(result) => inspect(@jsonpatch.json_equal(result, expected), content=\"true\")"
            )
            lines.append(
                "    Err(_) => inspect(\"expected success\", content=\"\")"
            )
            lines.append("  }")
        else:
            lines.append("  match @jsonpatch.apply_patch(doc, patch) {")
            lines.append(
                "    Ok(_) => inspect(\"expected failure\", content=\"\")"
            )
            lines.append("    Err(_) => inspect(true, content=\"true\")")
            lines.append("  }")
        lines.append("}")
        lines.append("")
    header = (
        f"// Included {included} of {len(cases)} upstream cases "
        f"({skipped} disabled upstream)."
    )
    lines.insert(2, header)
    return "\n".join(lines)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    total = 0
    for source in sorted(FIXTURES.glob("*.json")):
        text = gen_file(source)
        target = OUT / f"{source.stem}_wbtest.mbt"
        target.write_text(text, encoding="utf-8", newline="\n")
        count = text.count('test "')
        total += count
        print(f"{target.name}: {count} tests")
    print(f"total: {total} tests")


if __name__ == "__main__":
    main()
